<a href="https://colab.research.google.com/github/JazmineAlfaro/Topicos-en-Inteligencia-Artificial/blob/master/Laboratorio_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.arange(60).reshape(6,10)
#print(a)
mat = a[:, :6]
print(mat)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [3]:
print(mat[0,3:5])

[3 4]


In [4]:
print(mat[:,2])

[ 2 12 22 32 42 52]


In [5]:
print(mat[4:,4:6])

[[44 45]
 [54 55]]


In [6]:
print(mat[[2,4], :][:, [0,2,4]])

[[20 22 24]
 [40 42 44]]


In [7]:
print(mat[[2,4]][:,[0,2,4]])

[[20 22 24]
 [40 42 44]]
